entryPoints:
  web:
    address: ":80"
    #http:
    #  redirections:
    #    entryPoint:
    #      to: websecure
    #      scheme: https
  websecure:
    address: ":443"

providers:
  file:
    filename: "/etc/traefik/traefik_dynamic.yaml"

api:
  dashboard: true

log:
  level: DEBUG