entryPoints:
  web:
    address: ":80"
    #http:
    #  redirections:
    #    entryPoint:
    #      to: websecure
    #      scheme: https
  websecure:
    address: ":443"

certificatesResolvers:
  myresolver:
    acme:
      email: mischa.binder@stafag.ch
      storage: acme.json
      tlsChallenge:
        entryPoint: websecure

providers:
  file:
    filename: "/etc/traefik/traefik_dynamic.yaml"

log:
  level: DEBUG