http:
  routers:
    phishingBackend:
      rule: "Host(`securaware.ch`) && (Path(`/api`) || PathPrefix(`/api/`))"
      service: phishingBackend
      entrypoints:
        - websecure
      priority: 10
      tls:
        domains:
          - main: "securaware.ch"
        certResolver: myresolver

    phishingEducator:
      rule: "Host(`securaware.ch`)"
      service: phishingEducator
      entrypoints:
        - websecure
      priority: 1
      tls:
        domains:
          - main: "securaware.ch"
        certResolver: myresolver

    phishingDomains:
      rule: "HostRegexp(`{host:.+}`) && !Host(`securaware.ch`)"
      entrypoints:
        - web
        - websecure
      middlewares:
        - redirect-phishing-domains-to-securaware
      service: phishingEducator  # Not actually used, but required by traefik
  
  services:
    phishingBackend:
      loadBalancer:
        servers:
          - url: "http://phishing_backend:8080"

    phishingEducator:
      loadBalancer:
        servers:
          - url: "http://phishing_educator:80"

  middlewares:
    redirect-phishing-domains-to-securaware:
      redirectRegex:
        regex: "^(http[s]?:\/\/[^\/]+)?(\/[^?]+)?(\?[^#]+)?$"
        replacement: "https://securaware.ch/phishing-simulation?$${3}"
        permanent: true