entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

  websecure:
    address: ":443"

certificatesResolvers:
  myresolver:
    acme:
      email: mischa.binder@stafag.ch
      storage: /etc/traefik/acme/acme.json
      tlsChallenge: {}

providers:
  file:
    filename: "/etc/traefik/traefik_dynamic.yaml"

log:
  level: DEBUG