http:
  routers:
    phishingBackend:
      rule: "Path(`/api`) || PathPrefix(`/api/`)"
      service: phishingBackend
      entrypoints:
        - websecure
      priority: 10
      tls:
        domains:
          - main: "securaware.ch"
        certResolver: myresolver

    phishingEducator:
      rule: "Host(`securaware.ch`)"
      service: phishingEducator
      entrypoints:
        - websecure
      priority: 1
      tls:
        domains:
          - main: "securaware.ch"
        certResolver: myresolver
  
  services:
    phishingBackend:
      loadBalancer:
        servers:
          - url: "http://phishing_backend:8080"

    phishingEducator:
      loadBalancer:
        servers:
          - url: "http://phishing_educator:80"

  middlewares:
    traefik-auth:
      basicAuth:
        users:
          - "mib:$apr1$8Bm2OTIW$VNSGdjh2wfNmgMMbnKLw60"