http:
  routers:
    phishingBackend:
      rule: "Host(`securaware.ch`) && (Path(`/api`) || PathPrefix(`/api/`))"
      service: phishingBackend
      entrypoints:
        - websecure
      priority: 10
      tls:
        domains:
          - main: "securaware.ch"
        certResolver: myresolver

    phishingEducator:
      rule: "Host(`securaware.ch`)"
      service: phishingEducator
      entrypoints:
        - websecure
      priority: 1
      tls:
        domains:
          - main: "securaware.ch"
        certResolver: myresolver

    phishingDomains:
      rule: "HostRegexp(`{host:.+}`) && !Host(`securaware.ch`)"
      entrypoints:
        - web
        - websecure
      middlewares:
        - redirect-phishing-domains-to-securaware
      service: phishingEducator  # Not actually used, but required by traefik
  
  services:
    phishingBackend:
      loadBalancer:
        servers:
          - url: "http://phishing_backend:8080"

    phishingEducator:
      loadBalancer:
        servers:
          - url: "http://phishing_educator:80"

  middlewares:
    redirect-phishing-domains-to-securaware:
      chain:
        middlewares:
          - replace-path-to-education
          - redirect-to-securaware-https

    replace-path-to-education:
      replacePathRegex:
        regex: ".*"
        replacement: "/phishing-simulation"
      
    redirect-to-securaware-https:
      redirectScheme:
        scheme: https
        hostname: "securaware.ch"
        permanent: true