experimental:
  http3: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    http3:
      advertisedPort: "443"
  internal:
    address: ":8080"

providers:
  file:
    filename: "/etc/traefik/traefik_dynamic.yaml"

api: {}

log:
  level: DEBUG