image: golang:1.24.1

stages:
  - build
  - test

.goTesting:
  image: golang:1.24.1
  script:
    - go get -tool gotest.tools/gotestsum@latest

build:
  stage: build
  script:
    - cd PhishingBackend
    - go build -o /app/phishingBackend cmd/main.go
  artifacts:
    paths:
      - ./app/phishingBackend

test:
  extends: .goTesting
  stage: test
  script:
    - cd PhishingBackend
    - go tool gotestsum --junitfile testResults.xml
    # -  go test ./...
  artifacts:
    paths:
      - /**/testResults.xml