image: golang:1.24.1

stages:
  - build
  - test

build:
  stage: build
  script:
    - cd PhishingBackend
    - go build -o /app/phishingBackend cmd/main.go
  artifacts:
    paths:
      - ./app/phishingBackend

# https://gitlab.com/gitlab-org/gitlab/-/merge_requests/66787/diffs
test:
  stage: test
  script:
    - cd PhishingBackend
    - go get gotest.tools/gotestsum
    - gotestsum --junitfile testResults.xml
  artifacts:
    when: always
    paths:
      - PhishingBackend/testResults.xml
    reports:
      junit: PhishingBackend/testResults.xml