image: golang:1.24.1

stages:
  - build
  - test

build:
  stage: build
  script:
    - cd PhishingBackend
    - go build -o /app/phishingBackend cmd/main.go
  artifacts:
    paths:
      - ./app/phishingBackend

test:
  stage: test
  script:
    - cd PhishingBackend
    - go test ./...