// This file is auto-generated by @hey-api/openapi-ts

export type Lesson = {
    lessonId: string;
};

export type ExperienceGain = {
    newExperienceGained: number;
    totalExperience: number;
    newLevel?: number;
};

export type UserAuthentication = {
    email: string;
    password: string;
};

export type User = {
    firstname?: string;
    lastname?: string;
    email?: string;
    level?: number;
    totalExperience?: number;
};

export type UserPatchModel = {
    firstname?: string;
    lastname?: string;
    password?: string;
    email?: string;
};

export type UserPostModel = UserPatchModel & {
    [key: string]: unknown;
};

export type Exam = Array<Question>;

export type Question = {
    id?: number;
    question?: string;
    type?: 'single_choice' | 'multiple_choice';
    answers?: Array<Answer>;
};

export type Answer = {
    id?: number;
    answer?: string;
};

export type ExamCompletion = Array<QuestionCompletion>;

export type QuestionCompletion = {
    questionId?: number;
    answers?: Array<number>;
};

export type ExamValidation = {
    [key: string]: unknown;
};

export type CreateUserData = {
    body?: UserPostModel;
    path?: never;
    query?: never;
    url: '/users';
};

export type CreateUserErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type CreateUserResponses = {
    /**
     * User was created
     */
    201: unknown;
};

export type LoginAndReturnJwtTokenData = {
    body: UserAuthentication;
    path?: never;
    query?: never;
    url: '/users/login';
};

export type LoginAndReturnJwtTokenErrors = {
    /**
     * Authentication claims are invalid
     */
    400: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type LoginAndReturnJwtTokenResponses = {
    /**
     * JWT token
     */
    200: string;
};

export type LoginAndReturnJwtTokenResponse = LoginAndReturnJwtTokenResponses[keyof LoginAndReturnJwtTokenResponses];

export type GetUserData = {
    body?: never;
    path: {
        /**
         * Id of the course
         */
        userId: string;
    };
    query?: never;
    url: '/users/{userId}';
};

export type GetUserErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * User not found
     */
    404: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type GetUserResponses = {
    /**
     * todo
     */
    200: User;
};

export type GetUserResponse = GetUserResponses[keyof GetUserResponses];

export type UpdateUserData = {
    body?: UserPatchModel;
    path: {
        /**
         * Id of the course
         */
        userId: string;
    };
    query?: never;
    url: '/users/{userId}';
};

export type UpdateUserErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * User not found
     */
    404: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type UpdateUserResponses = {
    /**
     * User was updated
     */
    200: unknown;
};

export type CreateLessonCompletionData = {
    body: Lesson;
    path: {
        /**
         * Id of the course
         */
        courseId: number;
    };
    query?: never;
    url: '/courses/{courseId}/completions';
};

export type CreateLessonCompletionErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Lesson not found
     */
    404: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type CreateLessonCompletionResponses = {
    /**
     * Lesson completion newly created
     */
    201: ExperienceGain;
    /**
     * Lesson completion already exists
     */
    204: void;
};

export type CreateLessonCompletionResponse = CreateLessonCompletionResponses[keyof CreateLessonCompletionResponses];

export type GetExamsByExamIdData = {
    body?: never;
    path: {
        examId: string;
    };
    query?: never;
    url: '/exams/{examId}';
};

export type GetExamsByExamIdErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Exam not found
     */
    404: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type GetExamsByExamIdResponses = {
    /**
     * todo
     */
    200: Exam;
};

export type GetExamsByExamIdResponse = GetExamsByExamIdResponses[keyof GetExamsByExamIdResponses];

export type CompleteExamData = {
    body?: ExamCompletion;
    path: {
        examId: string;
    };
    query?: never;
    url: '/exams/{examId}/completions';
};

export type CompleteExamErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Exam not found
     */
    404: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type CompleteExamResponses = {
    /**
     * todo
     */
    200: ExamValidation;
};

export type CompleteExamResponse = CompleteExamResponses[keyof CompleteExamResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}/api` | (string & {});
};