services:
  phishing-backend:
    build:
      context: ../PhishingBackend
      dockerfile: .docker/Dockerfile
    env_file: ../PhishingBackend/.docker/phishing_backend.dev.env
    ports:
      - "8080:8080"