// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-fetch';
import type { CreateUserData, LoginAndReturnJwtTokenData, LoginAndReturnJwtTokenResponse, GetUserData, GetUserResponse, UpdateUserData, CreateLessonCompletionData, CreateLessonCompletionResponse, GetExamsByExamIdData, GetExamsByExamIdResponse, CompleteExamData, CompleteExamResponse } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * todo
 */
export const createUser = <ThrowOnError extends boolean = false>(options?: Options<CreateUserData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<unknown, unknown, ThrowOnError>({
        url: '/users',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Authenticates and authorizes the user and returns a JWT token if the authentication was successful.
 */
export const loginAndReturnJwtToken = <ThrowOnError extends boolean = false>(options: Options<LoginAndReturnJwtTokenData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<LoginAndReturnJwtTokenResponse, unknown, ThrowOnError>({
        url: '/users/login',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * todo
 */
export const getUser = <ThrowOnError extends boolean = false>(options: Options<GetUserData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetUserResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/users/{userId}',
        ...options
    });
};

/**
 * todo
 */
export const updateUser = <ThrowOnError extends boolean = false>(options: Options<UpdateUserData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).patch<unknown, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/users/{userId}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * TODO
 * TODO
 */
export const createLessonCompletion = <ThrowOnError extends boolean = false>(options: Options<CreateLessonCompletionData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateLessonCompletionResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/courses/{courseId}/completions',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * TODO
 * getExam
 */
export const getExamsByExamId = <ThrowOnError extends boolean = false>(options: Options<GetExamsByExamIdData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetExamsByExamIdResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/exams/{examId}',
        ...options
    });
};

/**
 * TODO
 * TODO
 */
export const completeExam = <ThrowOnError extends boolean = false>(options: Options<CompleteExamData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CompleteExamResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/exams/{examId}/completions',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};