// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-fetch';
import type { RegisterData, LoginAndReturnJwtTokenData, LoginAndReturnJwtTokenResponse, Todo1Data, Todo1Response, Todo2Data, CreateLessonCompletionData, CreateLessonCompletionResponse, Todo3Data, Todo3Response, Todo4Data, Todo4Response } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * todo
 */
export const register = <ThrowOnError extends boolean = false>(options?: Options<RegisterData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<unknown, unknown, ThrowOnError>({
        url: '/users',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Authenticates and authorizes the user and returns a JWT token if the authentication was successful.
 */
export const loginAndReturnJwtToken = <ThrowOnError extends boolean = false>(options: Options<LoginAndReturnJwtTokenData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<LoginAndReturnJwtTokenResponse, unknown, ThrowOnError>({
        url: '/users/login',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * todo
 */
export const todo1 = <ThrowOnError extends boolean = false>(options: Options<Todo1Data, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<Todo1Response, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/users/{userId}',
        ...options
    });
};

/**
 * todo
 */
export const todo2 = <ThrowOnError extends boolean = false>(options: Options<Todo2Data, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).patch<unknown, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/users/{userId}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * TODO
 * TODO
 */
export const createLessonCompletion = <ThrowOnError extends boolean = false>(options: Options<CreateLessonCompletionData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateLessonCompletionResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/courses/{courseId}/completions',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * TODO
 * TODO
 */
export const todo3 = <ThrowOnError extends boolean = false>(options: Options<Todo3Data, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<Todo3Response, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/exams/{examId}',
        ...options
    });
};

/**
 * TODO
 * TODO
 */
export const todo4 = <ThrowOnError extends boolean = false>(options: Options<Todo4Data, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<Todo4Response, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/exams/{examId}/completions',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};