// This file is auto-generated by @hey-api/openapi-ts

export type Lesson = {
    lessonId: number;
};

export type ExperienceGain = {
    newExperienceGained: number;
    totalExperience: number;
    newLevel?: number;
};

export type UserAuthentication = {
    username: string;
    password: string;
};

export type User = {
    firstname?: string;
    lastname?: string;
    password?: string;
    email?: string;
    level?: number;
    totalExperience?: number;
};

export type UserPatchModel = {
    firstname?: string;
    lastname?: string;
    password?: string;
    email?: string;
};

export type UserPostModel = User & {
    [key: string]: unknown;
};

export type Exam = Array<Question>;

export type Question = {
    id?: unknown;
    question?: string;
    type?: 'single_choice' | 'multiple_choice';
    answers?: Array<Answer>;
};

export type Answer = unknown;

export type ExamCompletion = Array<QuestionCompletion>;

export type QuestionCompletion = {
    questionId?: number;
    answers?: Array<number>;
};

export type ExamValidation = {
    placeholder?: string;
};

export type RegisterData = {
    body?: UserPostModel;
    path?: never;
    query?: never;
    url: '/users';
};

export type RegisterErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type RegisterResponses = {
    /**
     * User was created
     */
    201: unknown;
};

export type LoginAndReturnJwtTokenData = {
    body: UserAuthentication;
    path?: never;
    query?: never;
    url: '/users/login';
};

export type LoginAndReturnJwtTokenErrors = {
    /**
     * Authentication claims are invalid
     */
    400: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type LoginAndReturnJwtTokenResponses = {
    /**
     * JWT token
     */
    200: string;
};

export type LoginAndReturnJwtTokenResponse = LoginAndReturnJwtTokenResponses[keyof LoginAndReturnJwtTokenResponses];

export type Todo1Data = {
    body?: never;
    path: {
        /**
         * Id of the course
         */
        userId: string;
    };
    query?: never;
    url: '/users/{userId}';
};

export type Todo1Errors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * User not found
     */
    404: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type Todo1Responses = {
    /**
     * todo
     */
    200: User;
};

export type Todo1Response = Todo1Responses[keyof Todo1Responses];

export type Todo2Data = {
    body?: UserPatchModel;
    path: {
        /**
         * Id of the course
         */
        userId: string;
    };
    query?: never;
    url: '/users/{userId}';
};

export type Todo2Errors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * User not found
     */
    404: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type Todo2Responses = {
    /**
     * User was updated
     */
    200: unknown;
};

export type CreateLessonCompletionData = {
    body: Lesson;
    path: {
        /**
         * Id of the course
         */
        courseId: number;
    };
    query?: never;
    url: '/courses/{courseId}/completions';
};

export type CreateLessonCompletionErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Lesson not found
     */
    404: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type CreateLessonCompletionResponses = {
    /**
     * Lesson completion newly created
     */
    201: ExperienceGain;
    /**
     * Lesson completion already exists
     */
    204: void;
};

export type CreateLessonCompletionResponse = CreateLessonCompletionResponses[keyof CreateLessonCompletionResponses];

export type Todo3Data = {
    body?: never;
    path: {
        examId: string;
    };
    query?: never;
    url: '/exams/{examId}';
};

export type Todo3Errors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Exam not found
     */
    404: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type Todo3Responses = {
    /**
     * todo
     */
    200: Exam;
};

export type Todo3Response = Todo3Responses[keyof Todo3Responses];

export type Todo4Data = {
    body?: ExamCompletion;
    path: {
        examId: string;
    };
    query?: never;
    url: '/exams/{examId}/completions';
};

export type Todo4Errors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Exam not found
     */
    404: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type Todo4Responses = {
    /**
     * todo
     */
    200: ExamValidation;
};

export type Todo4Response = Todo4Responses[keyof Todo4Responses];

export type ClientOptions = {
    baseUrl: `${string}://${string}/api` | (string & {});
};